### ISSUE TITLE
AWS S3 can't find cropped image

### ISSUE THREAD

**Issue by OmegaHawkeye** [jonasundderwolf/django-image-cropping#169]
Hello,

I'm trying to use your project with AWS S3 Bucket as my Image Storage and it works fine in development but as soon as I'm turning off debug it gives me an 403 error on every image and it's probably bc of the cropped image name. My Problem is idk how to get ride of that weird name it gives the image like image.jpg.cropped_size-actual_size_cropper.jpg and bc there are commas in it aws replaces it with "%2c". 

My question now is if there is an easy fix I just don't see or do I need to save my images somewhere else?

I'm using:
- Django-Image-Cropper v.1.5.0
- Django-Storages v.1.11.1
- Django v.3.2.1

**Comment by MRigal** [comment]
Hi @OmegaHawkeye 
Thanks for the issue. Unfortunately cloud storages are not really supported. I know people who found workarounds, but we have several open issues with this scope. I am still a bit surprised because it normally won't produce a comma, just points and `x`...
We are not using the library in this context, so we had no need to implement it. Maybe in the future. However feel free to open a pull request!
Best,
Matthieu
