### ISSUE TITLE
The cropping widget not show on the backend admin

### ISSUE THREAD

**Issue by whmsysu** [jonasundderwolf/django-image-cropping#78]
I follow the steps list on the page and do the migration job for the project. But when I open the backend, i can only see the original image backend admin.

**Comment by romulocollopy** [comment]
Did you use the ImageCroppingMixin in Admin or the ModelForm widget?

**Comment by xfenix** [comment]
I have faced with this problem too. And i'm start digging, spent lot of time and finally found answer - if your image field has another widget already (like mine, field was defined like "ImagePreviewFIeld", not "models.ImageField" in my models.py), then image-cropping widget doesnt work.
So, maybe your problem is exactly like mine. Or maybe not. I just think that i need to warn you about this.

**Comment by unknownArtist** [comment]
I am also having this issue..

**Comment by anrie** [comment]
This looks pretty much like a configuration issue.
Make sure you follow the docs and check if the JS is correctly loaded.
You can look at the example app to see how things should be setup.

**Comment by unknownArtist** [comment]
thank @anrie 

I fixed it by setting the MEDIA_URL and MEDIA_ROOT in settings and urls.py
