### ISSUE TITLE
Cropping widget is not showing on client side?

### ISSUE THREAD

**Issue by sonus21** [jonasundderwolf/django-image-cropping#85]
I have installed cropping and it's dependencies and configure model to use ImageCropField but on client side it's still showing simple file widget. There is no preview as shown in the docs.
How to fix this error ?
Django:1.8.6
jQuery=2.1.4

**Comment by mnieber** [comment]
I had similar problems, that I solved using two steps:

First, use `ModelForm` for the form, and include the `cropping` field. In addition, as documented, specify the `ImageCropWidget` in the widgets option of the meta class._

```
from django import forms
from image_cropping import ImageCropWidget

class FooForm(forms.ModelForm):
    class Meta:
        widgets = {
            'image': ImageCropWidget,
        }

        model = Foo
        fields = ('image', 'cropping')
```

Second, make sure that you include the `cropping` field when displaying your form (if you include the entire form in your template using `{{ form }}` then you should be fine.


Question to the author of this repo: could you show us how to achieve this with a normal `forms.Form` instead of `forms.ModelForm`? I'm curious to see which `Field` members I would have to add to my form in this case.

**Comment by anrie** [comment]
@mnieber Actually specifying the widget explicitly [shouldn't even be necessary](https://github.com/jonasundderwolf/django-image-cropping/blob/master/example/forms.py#L5).

Basically it's required that you include both relevant fields (the `ImageCropField` and the `ImageRatioField`) and make sure that the correct widgets are used (that they are not overriden, etc.).
The rest of the magic happens in the [`image-cropping.js`](https://github.com/jonasundderwolf/django-image-cropping/blob/master/image_cropping/static/image_cropping/image_cropping.js) (which is included by the widget): Here the `ImageRatioField`gets hidden and replaced the with cropping widget, etc.

**Comment by mnieber** [comment]
@anrie You are right, it's usually not necessary. In my case, I was already using an `ImageField` from `sorl_thumbnails` for the image in my model, so I had to find a solution that doesn't involve `ImageCropField`.
